# Generated by Django 4.2.1 on 2023-05-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatbotmessage_embedding_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotmessage',
            name='referenced_urls',
            field=models.TextField(default=''),
        ),
    ]
