# Generated by Django 4.2.1 on 2023-05-20 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(default='', max_length=200)),
                ('title', models.CharField(default='', max_length=200)),
                ('content', models.TextField()),
                ('embedding', models.TextField()),
                ('related_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.baseurl')),
            ],
        ),
    ]
