# Generated by Django 4.2.1 on 2023-05-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapedpage',
            name='content',
        ),
        migrations.AddField(
            model_name='scrapedpage',
            name='content_to_embed',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='scrapedpage',
            name='full_html',
            field=models.TextField(default=''),
        ),
    ]
