# Generated by Django 4.2.1 on 2023-05-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_remove_scrapedpage_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseurl',
            name='is_scraped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scrapedpage',
            name='date_scraped',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapedpage',
            name='is_scraped',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scrapedpage',
            name='embedding',
            field=models.TextField(default=''),
        ),
    ]
