# Generated by Django 4.2.1 on 2023-05-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_baseurl_is_scraped_scrapedpage_date_scraped_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedpage',
            name='date_scraped',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
