# Generated by Django 4.2.1 on 2023-05-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_alter_scrapedpage_date_scraped'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedpage',
            name='date_embedded',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapedpage',
            name='is_embedded',
            field=models.BooleanField(default=False),
        ),
    ]
