# Generated by Django 4.2.1 on 2023-05-21 02:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_scrapedpage_date_embedded_scrapedpage_is_embedded'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedpage',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
