# Generated by Django 4.2.1 on 2023-05-21 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_scrapedpage_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapedpage',
            name='date_embedded',
        ),
        migrations.RemoveField(
            model_name='scrapedpage',
            name='embedding',
        ),
        migrations.RemoveField(
            model_name='scrapedpage',
            name='is_embedded',
        ),
    ]
