# Generated by Django 4.2.1 on 2023-05-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_embeddedcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='embeddedcontent',
            name='is_in_vector_database',
            field=models.BooleanField(default=False),
        ),
    ]
